### ISSUE TITLE
add first dive : as article 1

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [pokusio/apicurio-divein#2]
* Let's launch apicurio as quickly as possible, following https://www.apicur.io/studio/docs/getting-started-using-docker :
  * on the machine wher e I will run apicurio stack, of hostname `alien.io` : 
```bash
export HOSTNAME_OR_IP_OF_D_COMPOSE_MACHINE=192.168.1.28
export HOSTNAME_OR_IP_OF_D_COMPOSE_MACHINE=alien.io


git clone https://github.com/Apicurio/apicurio-studio.git
cd apicurio-studio/distro/docker-compose
cat Readme.md

# only those two type of databases are available
export DESIRED_DB_TYPE=mysql
export DESIRED_DB_TYPE=postgresql

# ---
# this is just a setup : nothing is started there
# among other things, [setup.sh] will populate values into the [./.env] file
# this setup.sh script makes use of [uuid-runtime] package
# ---
sudo apt-get install -y uuid-runtime
sudo ./setup.sh ${HOSTNAME_OR_IP_OF_D_COMPOSE_MACHINE} ${DESIRED_DB_TYPE}
./start-${DESIRED_DB_TYPE}-environment.sh
```

* on the machine from where I access to apicurio, in `/etc/hosts` : 
```ini
192.168.1.28 apicurio.alien.io microcks.alien.io keycloak.alien.io alien.io
```

* From the setup.sh, I get : 

```bash
jbl@pc-alienware-jbl:~/apicurio-studio/distro/docker-compose$ sudo ./setup.sh ${HOSTNAME_OR_IP_OF_D_COMPOSE_MACHINE} ${DESIRED_DB_TYPE}
Keycloak username: admin
Keycloak password: zmLfRB

Keycloak URL: alien.io:8090
Apicurio URL: alien.io:8093
Microcks URL: alien.io:8900

```
* If the first launch of `./start-${DESIRED_DB_TYPE}-environment.sh` fails to give you access to keycloak, apicurio etc.., then do this : 
  * execution  of `./start-${DESIRED_DB_TYPE}-environment.sh` is interactive, so first `Ctrl + C` :  this will tear downj the docker-compose
  * then re-launch `./start-${DESIRED_DB_TYPE}-environment.sh` 

* After that quirk, I could access all the stack : 
  * http://alien.io:8090/ : keycloak access, perfect$ly works with the `admin` username and the password displayed in stdout by the `./setup.sh` script 
  * http://alien.io:8093/ : that's apicurio studio. I had a problem accessing it, it turns out the problem lies into a keycloak openid connect misconfiguration (too bad...), the container logs are clear : 

```bash 
apicurio-studio-ui_1    | 2020-08-08 12:29:43,567 WARN  [org.keycloak.adapters.KeycloakDeployment] (default task-1) Failed to load URLs from http://alien.io:8090/auth/realms/apicurio/.well-known/openid-configuration: java.net.ConnectException: Connection timed out (Connection timed out)
apicurio-studio-ui_1    | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
apicurio-studio-ui_1    | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
apicurio-studio-ui_1    | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
apicurio-studio-ui_1    | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
apicurio-studio-ui_1    | 	at java.net.SocksSoc
```

  * http://alien.io:8900/ : last, and revealed not least, microcks (oh, yes, it rocks) : 
    * first thing, it perfectly works,
    * second thing, access to it is integrated to the keycloak service, and there is auto registering : so I can use this, imitate to fix the apicurio studio integration with keycloak
    * and look what you could do with microcks (actually rocks !!! ) : 

![microcks actually rocks](https://github.com/Jean-Baptiste-Lasselle/for-fellow-developers/raw/master/docuementation/impr.ecrans/apicurio-microcks/MICROCKS_EXCELLENT_FOR_TESTING_APIs_2020-08-08%2014-47-36.png)

![main things you can do with microcks.io](https://github.com/Jean-Baptiste-Lasselle/for-fellow-developers/raw/master/docuementation/impr.ecrans/apicurio-microcks/MICROCKS_IO_OH_MY_GOSH_2020-08-08%2014-58-16.png)
![created an api with miccroks in 3 clicks](https://github.com/Jean-Baptiste-Lasselle/for-fellow-developers/raw/master/docuementation/impr.ecrans/apicurio-microcks/MICROCKS_CREATED_AN_API_2020-08-08T12-49-36.393Z.png)

So ok, I may have not won to get apicurio studio yet : 
* but I will, problem is idetified and I have the microcks keycloak integration as a pattern fro the fix
* and I won one big thing, I believe, microcks.io
* and that's one of the things I was looking for : tooling to develop/test REST APis  (so here here I won a test tool)

**Comment by Jean-Baptiste-Lasselle** [comment]
also a 80 seconds videos showing creation of an api with apicurio, and creation of the mock with microcks, its just execllent : https://www.youtube.com/watch?v=69rZn9Q-qAE

Will really be ineresting to compare to / discuss `GraphQL`

**Comment by Jean-Baptiste-Lasselle** [comment]
Huummmm, I just understood the reference to Epicure , in Apicurio ... Humm

**Comment by Jean-Baptiste-Lasselle** [comment]
the https://github.com/grokify/swaggman tool, which generates Postman collection from Swagger, really is excellent completion of the stack.

**Comment by Jean-Baptiste-Lasselle** [comment]
switch from docker-compose to kubernetes as soon as possible and try as soon as possible the microcks opertor : https://operatorhub.io/operator/microcks


also : 

* https://operatorhub.io/operator/apicurio-registry
* tow recent helm charts one apicurio and the other sonarqube https://github.com/alphabox/charts/tree/master/charts

**Comment by Jean-Baptiste-Lasselle** [comment]
What is REALLY AWESOME : is that microcks.io integraties to PIPELINES (Circle CI / Travis CI etc...)

**Comment by Jean-Baptiste-Lasselle** [comment]
Hum, turns out that microcks service has the exact same issue with keyycloak, than apicurio, though wiht microck it does not prevent login: 

```bash
microcks                | 13:33:56.442 DEBUG 1 --- [  Thread-9] SoapUIMultiThreadedHttpConnectionManager : Closing connections idle longer than 30 SECONDS
microcks                | 13:33:57.903  WARN 1 --- [080-exec-9] o.k.adapters.KeycloakDeployment          : Failed to load URLs from http://alien.io:8090/auth/realms/microcks/.well-known/openid-configuration
microcks                | 
microcks                | java.net.ConnectException: Connection timed out (Connection timed out)
microcks                | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
microcks                | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
microcks                | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
microcks                | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
microcks                | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:363)
microcks                | 	at java.net.Socket.connect(Socket.java:607)
microcks                | 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
microcks                | 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
microcks                | 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
microcks                | 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
microcks                | 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
microcks                | 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
microcks                | 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
```

**Comment by Jean-Baptiste-Lasselle** [comment]
A small version of apicurio : https://github.com/Apicurio/apicurito

Ok, this one I could make it work in standalone mode : 

```bash

git clone git clone https://github.com/Apicurio/apicurito ~/apicurito

yarn && npm i -g @angular/cli && npm i

cd ui/

yarn && npm i && ng serve

```


![APi curito can do it for so many cases](https://github.com/Jean-Baptiste-Lasselle/for-fellow-developers/raw/master/docuementation/impr.ecrans/apicurio-microcks/APICURITO_2020-08-08%2016-02-58.png)
